// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using HelloWebApi.Console.Greetings.Models;
using Newtonsoft.Json.Linq;

namespace HelloWebApi.Console.Greetings.Models
{
    public static partial class GreetingCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Greeting> DeserializeJson(JToken inputObject)
        {
            IList<Greeting> deserializedObject = new List<Greeting>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Greeting greeting = new Greeting();
                greeting.DeserializeJson(iListValue);
                deserializedObject.Add(greeting);
            }
            return deserializedObject;
        }
    }
}
